name: Playwright Tests #nome do workflow
on: #trigger - define qnd vai ser executado
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: 
    
jobs: #tarefas q devem ser executadas
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest #workflow define quem vai rodar os testes/provisiona o ambiente p essa execução
    steps:
    - name: Get code
      uses: actions/checkout@v4 #uses - ativa plugin (recurso dentro do github actions)

    - name: Install node 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run E2E tests
      run: npx playwright test

    - name: Publish HTML report
      uses: actions/upload-artifact@v4 #pega o report HTML e publica na saida de execução do job/workflow
      if: always () #o report vai ser publicado mesmo se houver erros na exec
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
